# coding: utf-8

"""
    Cinema Ticket System API

    API for browsing cinema showings and ordering tickets. An order is created in a PENDING state (seats on hold), filled in step by step with PATCH, and then confirmed. If it is not confirmed before the hold expires, the order lapses on its own and the seats are released - no endpoint is called for that. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OrderPatchRequest(BaseModel):
    """
    Partial update - send only the fields you want to change. The raw card number is never stored; paymentToken comes from the payment gateway (Stripe, Tranzila, etc.). 
    """ # noqa: E501
    seats: Optional[List[StrictStr]] = Field(default=None, json_schema_extra={"examples": [["B3", "B4"]]})
    passenger_name: Optional[StrictStr] = Field(default=None, alias="passengerName", json_schema_extra={"examples": ["Rami"]})
    contact_email: Optional[StrictStr] = Field(default=None, alias="contactEmail")
    payment_token: Optional[StrictStr] = Field(default=None, alias="paymentToken", json_schema_extra={"examples": ["tok_1Kx9aB2eZvKYlo2C"]})
    __properties: ClassVar[List[str]] = ["seats", "passengerName", "contactEmail", "paymentToken"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderPatchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrderPatchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "seats": obj.get("seats"),
            "passengerName": obj.get("passengerName"),
            "contactEmail": obj.get("contactEmail"),
            "paymentToken": obj.get("paymentToken")
        })
        return _obj


